# Generated by Django 3.0.8 on 2020-08-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_dinnerplatters_pasta_salads_sicilianpizza_subs_toppings'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularpizza',
            name='pizza_type',
            field=models.CharField(default='RegularPizza', max_length=64),
        ),
    ]
