# Generated by Django 3.0.8 on 2020-08-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_regularpizza_pizza_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinnerplatters',
            name='pizza_type',
            field=models.CharField(default='DinnerPlatters', max_length=64),
        ),
        migrations.AddField(
            model_name='pasta',
            name='pizza_type',
            field=models.CharField(default='Pasta', max_length=64),
        ),
        migrations.AddField(
            model_name='salads',
            name='pizza_type',
            field=models.CharField(default='Salads', max_length=64),
        ),
        migrations.AddField(
            model_name='sicilianpizza',
            name='pizza_type',
            field=models.CharField(default='SicilianPizza', max_length=64),
        ),
        migrations.AddField(
            model_name='subs',
            name='pizza_type',
            field=models.CharField(default='Subs', max_length=64),
        ),
        migrations.AddField(
            model_name='toppings',
            name='pizza_type',
            field=models.CharField(default='Toppings', max_length=64),
        ),
    ]
