# Generated by Django 3.0.8 on 2020-08-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200830_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dinner_platters', models.ManyToManyField(blank=True, related_name='dinner_platters', to='orders.DinnerPlatters')),
                ('pasta', models.ManyToManyField(blank=True, related_name='pasta', to='orders.Pasta')),
                ('regular_pizza', models.ManyToManyField(blank=True, related_name='regular_pizza', to='orders.RegularPizza')),
                ('salads', models.ManyToManyField(blank=True, related_name='salads', to='orders.Salads')),
                ('sicilian_pizza', models.ManyToManyField(blank=True, related_name='sicilian_pizza', to='orders.SicilianPizza')),
                ('subs', models.ManyToManyField(blank=True, related_name='subs', to='orders.Subs')),
                ('toppings', models.ManyToManyField(blank=True, related_name='toppings', to='orders.Toppings')),
            ],
        ),
    ]
