# Generated by Django 3.0.8 on 2020-09-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200902_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order',
            field=models.ManyToManyField(related_name='cart', to='orders.Order'),
        ),
    ]
