# Generated by Django 3.0.8 on 2020-09-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200902_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order',
        ),
        migrations.AlterField(
            model_name='order',
            name='regular_pizza',
            field=models.ManyToManyField(blank=True, related_name='regular_pizza', to='orders.RegularPizza'),
        ),
    ]
