# Generated by Django 3.0.8 on 2020-09-04 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_remove_cart_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='orders.Order'),
        ),
    ]
