# Generated by Django 3.0.8 on 2020-09-05 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0018_auto_20200905_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regpizcart',
            name='regular_pizza',
        ),
        migrations.AddField(
            model_name='regpizcart',
            name='reg_piz',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='reg_pizza', to='orders.RegularPizza'),
        ),
        migrations.AlterField(
            model_name='regpizcart',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='regpizcart',
            name='size',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='regpizcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_of_cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
