# Generated by Django 3.0.8 on 2020-09-05 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20200905_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regpizcart',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='regpizcart',
            name='size',
            field=models.BooleanField(),
        ),
    ]
