# Generated by Django 3.0.8 on 2020-09-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20200905_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regpizcart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='regpizcart',
            name='size',
            field=models.BooleanField(default=False),
        ),
    ]
