# Generated by Django 3.0.8 on 2020-09-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_auto_20200905_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regpizcart',
            name='regular_pizza',
            field=models.ManyToManyField(blank=True, default='', related_name='reg_pizza', to='orders.RegularPizza'),
        ),
    ]
