# Generated by Django 3.0.8 on 2020-09-05 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_auto_20200905_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularPizzaOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('size', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='dinner_platters',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pasta',
        ),
        migrations.RemoveField(
            model_name='order',
            name='regular_pizza',
        ),
        migrations.RemoveField(
            model_name='order',
            name='salads',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sicilian_pizza',
        ),
        migrations.RemoveField(
            model_name='order',
            name='subs',
        ),
        migrations.RemoveField(
            model_name='order',
            name='toppings',
        ),
        migrations.DeleteModel(
            name='RegPizCart',
        ),
        migrations.AddField(
            model_name='regularpizzaorder',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reg_order', to='orders.Cart'),
        ),
        migrations.AddField(
            model_name='regularpizzaorder',
            name='regular_pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regular_pizza', to='orders.RegularPizza'),
        ),
    ]
