# Generated by Django 3.0.8 on 2020-09-05 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_auto_20200905_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='SicilianPizzaOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('size', models.BooleanField(default=False)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sic_order', to='orders.Cart')),
                ('sicilian_pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sicilian_pizza', to='orders.RegularPizza')),
            ],
        ),
    ]
