# Generated by Django 3.0.8 on 2020-09-05 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_sicilianpizzaorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sicilianpizzaorder',
            name='sicilian_pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sicilian_pizza', to='orders.SicilianPizza'),
        ),
    ]
