# Generated by Django 3.0.8 on 2020-09-05 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_subsorder_toppingsorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regularpizzaorder',
            old_name='regular_pizza',
            new_name='dish',
        ),
        migrations.RenameField(
            model_name='sicilianpizzaorder',
            old_name='sicilian_pizza',
            new_name='dish',
        ),
        migrations.RenameField(
            model_name='subsorder',
            old_name='sicilian_pizza',
            new_name='dish',
        ),
        migrations.RenameField(
            model_name='toppingsorder',
            old_name='sicilian_pizza',
            new_name='dish',
        ),
        migrations.CreateModel(
            name='PastaOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pas_order', to='orders.Cart')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasta', to='orders.Pasta')),
            ],
        ),
    ]
