# Generated by Django 3.0.8 on 2020-09-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_dinnerplattersorder_saladsorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinnerplattersorder',
            name='size',
            field=models.CharField(default='Small', max_length=64),
        ),
        migrations.AlterField(
            model_name='regularpizzaorder',
            name='size',
            field=models.CharField(default='Small', max_length=64),
        ),
        migrations.AlterField(
            model_name='sicilianpizzaorder',
            name='size',
            field=models.CharField(default='Small', max_length=64),
        ),
        migrations.AlterField(
            model_name='subsorder',
            name='size',
            field=models.CharField(default='Small', max_length=64),
        ),
    ]
