# Generated by Django 3.0.8 on 2020-09-11 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_cart'),
        ('orders', '0038_auto_20200907_1221'),
    ]

    operations = [
    ]
