# Generated by Django 3.0.8 on 2020-09-13 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_auto_20200911_0931'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
