# Generated by Django 3.0.8 on 2020-09-13 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0042_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
