# Generated by Django 3.0.8 on 2020-09-13 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0043_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toppingsorder',
            name='quantity',
        ),
    ]
